"use client";
import { db } from "@/lib/db";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jsEiL0r4EyG
 */

import TodoView from "./todo/view/TodoView";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    return () => {
      db.close();
    };
  }, []);

  return (
    <main className="flex flex-col items-center justify-center min-h-screen py-2">
      <TodoView />
    </main>
  );
}
